# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tilemapscalelevels.ui'
#
# Created: Mon Jan  6 15:47:04 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DockWidgetTileMapScaleLevels(object):
    def setupUi(self, DockWidgetTileMapScaleLevels):
        DockWidgetTileMapScaleLevels.setObjectName(_fromUtf8("DockWidgetTileMapScaleLevels"))
        DockWidgetTileMapScaleLevels.resize(262, 317)
        DockWidgetTileMapScaleLevels.setMinimumSize(QtCore.QSize(262, 317))
        DockWidgetTileMapScaleLevels.setMaximumSize(QtCore.QSize(262, 317))
        DockWidgetTileMapScaleLevels.setFloating(False)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxIsActive = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBoxIsActive.setChecked(True)
        self.checkBoxIsActive.setTristate(False)
        self.checkBoxIsActive.setObjectName(_fromUtf8("checkBoxIsActive"))
        self.horizontalLayout.addWidget(self.checkBoxIsActive)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonInfo = QtGui.QToolButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInfo.setIcon(icon)
        self.buttonInfo.setIconSize(QtCore.QSize(22, 22))
        self.buttonInfo.setObjectName(_fromUtf8("buttonInfo"))
        self.horizontalLayout.addWidget(self.buttonInfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBoxUseMercator = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBoxUseMercator.setChecked(False)
        self.checkBoxUseMercator.setTristate(False)
        self.checkBoxUseMercator.setObjectName(_fromUtf8("checkBoxUseMercator"))
        self.verticalLayout_2.addWidget(self.checkBoxUseMercator)
        self.checkBoxUseOnTheFlyTransformation = QtGui.QCheckBox(self.dockWidgetContents)
        self.checkBoxUseOnTheFlyTransformation.setChecked(False)
        self.checkBoxUseOnTheFlyTransformation.setTristate(False)
        self.checkBoxUseOnTheFlyTransformation.setObjectName(_fromUtf8("checkBoxUseOnTheFlyTransformation"))
        self.verticalLayout_2.addWidget(self.checkBoxUseOnTheFlyTransformation)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sliderZoomlevels = QtGui.QSlider(self.groupBox)
        self.sliderZoomlevels.setToolTip(_fromUtf8(""))
        self.sliderZoomlevels.setStatusTip(_fromUtf8(""))
        self.sliderZoomlevels.setMaximum(25)
        self.sliderZoomlevels.setSliderPosition(0)
        self.sliderZoomlevels.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoomlevels.setTickPosition(QtGui.QSlider.NoTicks)
        self.sliderZoomlevels.setTickInterval(0)
        self.sliderZoomlevels.setObjectName(_fromUtf8("sliderZoomlevels"))
        self.verticalLayout.addWidget(self.sliderZoomlevels)
        self.spinBoxZoomlevels = QtGui.QSpinBox(self.groupBox)
        self.spinBoxZoomlevels.setKeyboardTracking(False)
        self.spinBoxZoomlevels.setMaximum(25)
        self.spinBoxZoomlevels.setObjectName(_fromUtf8("spinBoxZoomlevels"))
        self.verticalLayout.addWidget(self.spinBoxZoomlevels)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBoxDatasets = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxDatasets.setObjectName(_fromUtf8("groupBoxDatasets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxDatasets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonLoadOSM = QtGui.QToolButton(self.groupBoxDatasets)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/osm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadOSM.setIcon(icon1)
        self.buttonLoadOSM.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadOSM.setObjectName(_fromUtf8("buttonLoadOSM"))
        self.horizontalLayout_2.addWidget(self.buttonLoadOSM)
        self.comboBoxUserDatasets = QtGui.QComboBox(self.groupBoxDatasets)
        self.comboBoxUserDatasets.setObjectName(_fromUtf8("comboBoxUserDatasets"))
        self.horizontalLayout_2.addWidget(self.comboBoxUserDatasets)
        self.buttonLoadRefreshUserDatasets = QtGui.QToolButton(self.groupBoxDatasets)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadRefreshUserDatasets.setIcon(icon2)
        self.buttonLoadRefreshUserDatasets.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadRefreshUserDatasets.setObjectName(_fromUtf8("buttonLoadRefreshUserDatasets"))
        self.horizontalLayout_2.addWidget(self.buttonLoadRefreshUserDatasets)
        self.buttonLoadUserDataset = QtGui.QToolButton(self.groupBoxDatasets)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadUserDataset.setIcon(icon3)
        self.buttonLoadUserDataset.setIconSize(QtCore.QSize(22, 22))
        self.buttonLoadUserDataset.setObjectName(_fromUtf8("buttonLoadUserDataset"))
        self.horizontalLayout_2.addWidget(self.buttonLoadUserDataset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBoxDatasets)
        DockWidgetTileMapScaleLevels.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidgetTileMapScaleLevels)
        QtCore.QMetaObject.connectSlotsByName(DockWidgetTileMapScaleLevels)

    def retranslateUi(self, DockWidgetTileMapScaleLevels):
        DockWidgetTileMapScaleLevels.setWindowTitle(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Tile Map Scale Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIsActive.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setToolTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Show information", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setStatusTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Show information", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInfo.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseMercator.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Use World Mercator System", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseOnTheFlyTransformation.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Use \'On-The-Fly\' Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Zoomlevel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDatasets.setTitle(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "Datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setToolTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "load OSM Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setStatusTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "load OSM Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadOSM.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setToolTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "refresh list of datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setStatusTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "refresh list of datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadRefreshUserDatasets.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setToolTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "load selected dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setStatusTip(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "load selected dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLoadUserDataset.setText(QtGui.QApplication.translate("DockWidgetTileMapScaleLevels", "OSM", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
